app/home/forms.py
from flask.ext.wtf import Form
from wtforms import StringField, TextAreaField, SelectField
from wtforms.validators import DataRequired

class BlogForm(Form):
    title = StringField('title', [DataRequired('Title is required')])
    content = TextAreaField('content', [DataRequired('Body is required')])
    category = SelectField('category')

class SearchForm(Form):
    keyword = StringField('keyword')

app/home/views.py
from app import app, db
from flask import render_template, redirect, url_for, flash, request, Blueprint
from flask.ext.login import login_required, current_user
from .forms import BlogForm, SearchForm
from app.models import Blog, Category, User
from markdown import markdown
from sqlalchemy import desc
from datetime import datetime

home_blueprint = Blueprint(
    'home', __name__,
    template_folder='templates'
)

@home_blueprint.route('/', methods=['GET', 'POST'])
@home_blueprint.route('/index/<int:page>', methods=['GET', 'POST'])
def index(page=1):
    form = SearchForm()
    if form.validate_on_submit():
        results = Blog.query.filter(Blog.content.like('%' + form.keyword.data + '%'))
        if results.all():
            flash('Found with [' + form.keyword.data + '] blog.')
            posts = results.paginate(page, app.config['POSTS_PER_PAGE'], False)
            hot_posts = Blog.query.order_by(desc(Blog.pub_date)).limit(app.config['HOT_POSTS_COUNT']).all()
            return render_template('index.html', posts=posts, hot_posts=hot_posts, form=form)
        else:
            flash('Not found with [' + form.keyword.data + '] blog.')
            return redirect(url_for('home.index'))
    posts = Blog.query.order_by(desc(Blog.pub_date)).paginate(page, app.config['POSTS_PER_PAGE'], False)
    hot_posts = Blog.query.order_by(desc(Blog.pub_date)).limit(app.config['HOT_POSTS_COUNT']).all()
    return render_template('index.html', posts=posts, hot_posts=hot_posts, form=form)

@home_blueprint.route('/article/<article_id>')
def article(article_id):
    post = Blog.query.filter_by(id=article_id,).first()
    format_content = markdown(post.content, ['markdown.extensions.extra'])
    return render_template('article.html', post=post, content=format_content)

@home_blueprint.route('/article/<article_id>/edit', methods=['GET', 'POST'])
def article_edit(article_id):
    form = BlogForm()
    post = Blog.query.filter_by(id=article_id,).first()
    choices = Category.get_all()
    form.category.choices = choices
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        post.author_id = current_user.id
        post.category_id = form.category.data
        post.pub_date = datetime.utcnow()
        db.session.add(post)
        db.session.commit()
        flash('Update blog sucessfully!')
        return redirect(url_for('home.article', article_id=post.id))   
    form.title.data = post.title
    form.content.data = post.content
    form.category.data = post.category_id
    return render_template('publish.html', form=form)

@home_blueprint.route('/article/<article_id>/delete')
@login_required
def article_del(article_id):
    post = Blog.query.filter_by(id=article_id).first()
    if current_user.name == post.author.name or current_user.name == 'boer':
        db.session.delete(post)
        db.session.commit()
        flash('Delete blog success!')
        return redirect(url_for('home.index'))
    else:
        flash('You are not Superuser!')
        return redirect(url_for('home.index'))

@home_blueprint.route('/category/<category_name>')
def category(category_name):
    category = Category.query.filter_by(name=category_name).first()
    posts = Blog.query.filter_by(category_id=category.id).all()
    return render_template('category.html', posts=posts)

@home_blueprint.route('/publish', methods=['GET', 'POST'])
def publish():
    form = BlogForm()
    choices = Category.get_all()
    form.category.choices = choices
    if form.validate_on_submit():
        post = Blog(form.title.data, form.content.data, current_user.id, form.category.data)
        db.session.add(post)
        db.session.commit()
        flash('Publish blog success!')
        return redirect(url_for('home.index'))
    return render_template('publish.html', form=form)

app/home/templates/article.html
{% extends 'base.html' %}

{% block head %}
<link href="//cdn.bootcss.com/highlight.js/9.0.0/styles/monokai-sublime.min.css" rel="stylesheet">
<script src="//cdn.bootcss.com/highlight.js/9.0.0/highlight.min.js"></script>
<script>hljs.initHighlightingOnLoad();</script>
{% endblock %}

{% block content %}
<div class="uk-width-7-10">
    <!-- start article list  -->
    <article class="uk-article">
        <h1 class="uk-article-title">{{ post.title }}</h1>
        <p class="uk-article-meta">
            <i class="uk-icon-user"></i> {{ post.author.name }}&nbsp;&nbsp;
            <i class="uk-icon-calendar"></i> {{ post.pub_date.strftime('%Y-%m-%d %X') }}&nbsp;&nbsp;
            {% if current_user.name == post.author.name or current_user.name == 'boer' %}
            <a style="color: #999;" href="{{ url_for('home.article_del', article_id=post.id) }}" class="uk-animation-hover uk-animation-shake z_delete"><i class="uk-icon-trash"> Delete</i></a>&nbsp;&nbsp;
            <a style="color: #999;" href="{{ url_for('home.article_edit', article_id=post.id) }}" class="uk-animation-hover uk-animation-fade"><i class="uk-icon-edit"> Edit</i></a>&nbsp;&nbsp;
            {% endif %}
        </p>
        <!-- <p class="uk-article-lead" ></p> -->
        {{ content|safe }}
        <!-- <hr class="uk-article-divider"> -->
        <wb:share-button addition="simple" type="button" ralateUid="2770931324"></wb:share-button>
    </article>
    <!-- 多说评论框 start -->
    <div class="ds-thread" data-thread-key="{{ post.id }}" data-title="{{ post.title }}" data-url="{{ url_for('home.article', article_id=post.id) }}"></div>
    <!-- 多说评论框 end -->
    <!-- 多说公共JS代码 start (一个网页只需插入一次) -->
    <script type="text/javascript">
    var duoshuoQuery = {short_name:"boer"};
        (function() {
            var ds = document.createElement('script');
            ds.type = 'text/javascript';ds.async = true;
            ds.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') + '//static.duoshuo.com/embed.js';
            ds.charset = 'UTF-8';
            (document.getElementsByTagName('head')[0]
             || document.getElementsByTagName('body')[0]).appendChild(ds);
        })();
        // Add by boer for delete artile prompt.
        $('.z_delete').on('click', function() {
            var _this =$(this);
            UIkit.modal.confirm('Are you sure delete?', function() {
                window.location.href=_this.attr('href');
            });
            return false;
        });
    </script>
    <!-- 多说公共JS代码 end -->

    <!-- end article list  -->
</div>

<div class="uk-width-3-10">
    <div class="uk-panel uk-panel-header">
        <h3 class="uk-h4">Follow Me</h3>
        <p>
            <a href="http://weibo.com/boerutopia" class="uk-icon-button uk-icon-weibo"></a>
            <a href="https://github.com/boer0924" class="uk-icon-button uk-icon-github"></a>
            <a href="https://twitter.com/boerutopia" class="uk-icon-button uk-icon-twitter"></a>
            <a href="http://user.qzone.qq.com/244857967" class="uk-icon-button uk-icon-qq"></a>
        </p>
    </div>
    <div class="uk-panel uk-panel-header">
        <iframe width="100%" height="550" class="share_self"  frameborder="0" scrolling="no" src="http://widget.weibo.com/weiboshow/index.php?language=&width=0&height=550&fansRow=2&ptype=1&speed=0&skin=1&isTitle=0&noborder=1&isWeibo=1&isFans=1&uid=2770931324&verifier=6810783f&dpc=1"></iframe>
    </div>
</div>
{% endblock %}

app/home/templates/category.html
{% extends 'base.html' %}
{% block content %}
<div class="uk-width-7-10">
    <!-- start article list  -->
    <ul class="uk-list uk-list-line">
        {% for post in posts %}
        <li>
            <a href="{{ url_for('home.article', article_id=post.id) }}">{{ post.title }}</a>
        </li>
    {% endfor %}
    </ul>
    <!-- end article list  -->
</div>

<div class="uk-width-3-10">
    <div class="uk-panel">
        <wb:follow-button uid="2770931324" type="red_4" width="100%" height="64" ></wb:follow-button>
    </div>
    <div class="uk-panel uk-panel-header">
        <h3 class="uk-panel-title">友情链接</h3>
        <ul class="uk-list uk-list-line">
            <li><i class="uk-icon-thumbs-o-up"></i> <a target="_blank" href="#">编程</a></li>
            <li><i class="uk-icon-thumbs-o-up"></i> <a target="_blank" href="#">读书</a></li>
            <li><i class="uk-icon-thumbs-o-up"></i> <a target="_blank" href="#">Python教程</a></li>
            <li><i class="uk-icon-thumbs-o-up"></i> <a target="_blank" href="#">Git教程</a></li>
        </ul>
    </div>
    <div class="uk-panel uk-panel-header">
        <h3 class="uk-h4">Follow Me</h3>
        <p>
            <a href="http://weibo.com/boerutopia" class="uk-icon-button uk-icon-weibo"></a>
            <a href="https://github.com/boer0924" class="uk-icon-button uk-icon-github"></a>
            <a href="https://twitter.com/boerutopia" class="uk-icon-button uk-icon-twitter"></a>
            <a href="http://user.qzone.qq.com/244857967" class="uk-icon-button uk-icon-qq"></a>
        </p>
    </div>
</div>
{% endblock %}

app/home/templates/index.html
{% extends 'base.html' %}
{% block nav %}
<li>
    <form class="uk-form uk-margin-remove uk-display-inline-block" method="post">
        {{ form.csrf_token }}
        {{ form.keyword(style="margin-top:5px;border-radius:8px;", placeholder="Search") }}
    </form>
</li>
{% endblock %}
{% block content %}
<div class="uk-width-7-10">
    {% if posts %}
    <!-- start article list  -->
    <ul class="uk-list uk-list-striped">
        {% for post in posts.items %}
        <li>
            <a style="margin-left: 10px;" href="{{ url_for('home.article', article_id=post.id) }}">{{ post.title }}</a>
            <span style="float: right; margin-right: 20px;">{{ post.pub_date.strftime('%Y-%m-%d') }}</span>
        </li>
        {% endfor %}
    </ul>
    <!-- end article list  -->
    {% else %}
    <script type="text/javascript">
        alert('Not Found');
    </script>
    {% endif %}
    <!-- start paginate -->
    <ul class="uk-pagination">
        {% if posts.has_prev %}
        <li class="uk-disabled"><a href="{{ url_for('home.index', page=posts.prev_num) }}"><span><i class="uk-icon-angle-double-left"></i></span></a></li>
        {% endif %}

        {% if posts.pages > 1 %}
            {% for p in posts.iter_pages() %}
                {% if p == posts.page %}
                    <li class="uk-active"><span><a href="{{ url_for('home.index', page=p) }}">{{ p }}</a></span></li>
                {% elif not p %}
                    <li><span>...</span></li>
                {% else %}
                    <li class="uk-disabled"><span><a href="{{ url_for('home.index', page=p) }}">{{ p }}</a></span></li>
                {% endif %}
            {% endfor %}
        {% endif %}
        
        {% if posts.has_next %}
        <li class="uk-disabled"><a href="{{ url_for('home.index', page=posts.next_num) }}"><span><i class="uk-icon-angle-double-right"></i></span></a></li>
        {% endif %}
    </ul>
    <!-- end paginate -->
</div>

<div class="uk-width-3-10">
    <div class="uk-panel">
        <wb:follow-button uid="2770931324" type="red_4" width="100%" height="64" ></wb:follow-button>
    </div>
    <div class="uk-panel uk-panel-header">
        <h3 class="uk-panel-title">最新文章</h3>
        <ul class="uk-list uk-list-line">
            {% for post in hot_posts %}
            <li><i class="uk-icon-file-word-o"></i> <a href="{{ url_for('home.article', article_id=post.id) }}">{{ post.title }}</a></li>
            {% endfor %}
        </ul>
    </div>
    <div class="uk-panel uk-panel-header">
        <h3 class="uk-h4">Follow Me</h3>
        <p>
            <a href="http://weibo.com/boerutopia" class="uk-icon-button uk-icon-weibo"></a>
            <a href="https://github.com/boer0924" class="uk-icon-button uk-icon-github"></a>
            <a href="https://twitter.com/boerutopia" class="uk-icon-button uk-icon-twitter"></a>
            <a href="http://user.qzone.qq.com/244857967" class="uk-icon-button uk-icon-qq"></a>
        </p>
    </div>
    <div class="uk-panel uk-panel-header">
        <h3 class="uk-panel-title">友情链接</h3>
        <ul class="uk-list uk-list-space">
            <li><i class="uk-icon-thumbs-o-up"></i> <a target="_blank" href="#">编程</a></li>
            <li><i class="uk-icon-thumbs-o-up"></i> <a target="_blank" href="#">读书</a></li>
            <li><i class="uk-icon-thumbs-o-up"></i> <a target="_blank" href="#">Python教程</a></li>
            <li><i class="uk-icon-thumbs-o-up"></i> <a target="_blank" href="#">Git教程</a></li>
        </ul>
    </div>
</div>
{% endblock %}

app/home/templates/publish.html
{% extends 'base.html' %}
{% block head %}
        <link href="//cdn.bootcss.com/codemirror/5.9.0/codemirror.min.css" rel="stylesheet">
        <link href="//cdn.bootcss.com/uikit/2.24.2/css/components/htmleditor.almost-flat.min.css" rel="stylesheet">
        <link href="//cdn.bootcss.com/uikit/2.24.2/css/components/htmleditor.gradient.min.css" rel="stylesheet">
        <link href="//cdn.bootcss.com/uikit/2.24.2/css/components/htmleditor.min.css" rel="stylesheet">
        <script src="//cdn.bootcss.com/marked/0.3.5/marked.min.js"></script>
        <script src="//cdn.bootcss.com/codemirror/5.9.0/codemirror.min.js"></script>
        <script src="//cdn.bootcss.com/codemirror/5.9.0/mode/markdown/markdown.min.js"></script>
        <script src="//cdn.bootcss.com/codemirror/5.9.0/addon/mode/overlay.min.js"></script>
        <script src="//cdn.bootcss.com/codemirror/5.9.0/mode/xml/xml.min.js"></script>
        <script src="//cdn.bootcss.com/codemirror/5.9.0/mode/gfm/gfm.min.js"></script>
        <script src="//cdn.bootcss.com/uikit/2.24.2/js/components/htmleditor.min.js"></script>
{% endblock %}
{% block content %}
<!-- start comment -->
<form action="" method="post" name="post" style="padding: 25px;" class="uk-form uk-form-stacked">
    {{ form.csrf_token }}
    <div class="uk-form-row">
        <label class="uk-form-label" for="">Title</label>
        <div class="uk-form-controls">
            {{ form.title(style="width: 910px;") }}
        </div>
    </div>
    <div class="uk-form-row">
        <label class="uk-form-label" for="">Content</label>
        <div class="uk-form-controls">
            {{ form.content(id="z-htmleditor") }}
        </div>
    </div>
    <div class="uk-form-row">
        <label class="uk-form-label" for="">Category</label>
        <div class="uk-form-controls">
            {{ form.category }}
        </div>
    </div>
    <div class="uk-form-row">
        <div class="uk-form-controls">
            <button type="submit" class="uk-button uk-button-primary">Submit</button>
        </div>
    </div>
    <!-- {% for error in form.errors %}
    <script type="text/javascript">
        UIkit.notify({
            message : '{{ error }}',
            status : 'danger',
            timeout : 5000,
            pos : 'top-center'
        });
    </script>
    {% endfor %} -->
</form>
<script type="text/javascript">
    var htmleditor = UIkit.htmleditor($('#z-htmleditor'), {markdown:true, mode:'tab', maxsplitsize:600});
</script>
<!-- end comment -->
{% endblock %}