app/home/views.py
from app import app, db
from flask import render_template, redirect, url_for, flash, request, Blueprint
from flask.ext.login import login_required, current_user
from .forms import BlogForm, SearchForm
from app.models import Blog, Category, User
from markdown import markdown
from sqlalchemy import desc
from datetime import datetime

home_blueprint = Blueprint(
    'home', __name__,
    template_folder='templates'
)

@home_blueprint.route('/', methods=['GET', 'POST'])
@home_blueprint.route('/index/<int:page>', methods=['GET', 'POST'])
def index(page=1):
    form = SearchForm()
    if form.validate_on_submit():
        results = Blog.query.filter(Blog.content.like('%' + form.keyword.data + '%'))
        if results.all():
            flash('Found with [' + form.keyword.data + '] blog.')
            posts = results.paginate(page, app.config['POSTS_PER_PAGE'], False)
            hot_posts = Blog.query.order_by(desc(Blog.pub_date)).limit(app.config['HOT_POSTS_COUNT']).all()
            return render_template('index.html', posts=posts, hot_posts=hot_posts, form=form)
        else:
            flash('Not found with [' + form.keyword.data + '] blog.')
            return redirect(url_for('home.index'))
    posts = Blog.query.order_by(desc(Blog.pub_date)).paginate(page, app.config['POSTS_PER_PAGE'], False)
    hot_posts = Blog.query.order_by(desc(Blog.pub_date)).limit(app.config['HOT_POSTS_COUNT']).all()
    return render_template('index.html', posts=posts, hot_posts=hot_posts, form=form)

@home_blueprint.route('/article/<article_id>')
def article(article_id):
    post = Blog.query.filter_by(id=article_id,).first()
    format_content = markdown(post.content, ['markdown.extensions.extra'])
    return render_template('article.html', post=post, content=format_content)

@home_blueprint.route('/article/<article_id>/edit', methods=['GET', 'POST'])
def article_edit(article_id):
    form = BlogForm()
    post = Blog.query.filter_by(id=article_id,).first()
    choices = Category.get_all()
    form.category.choices = choices
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        post.author_id = current_user.id
        post.category_id = form.category.data
        post.pub_date = datetime.utcnow()
        db.session.add(post)
        db.session.commit()
        flash('Update blog sucessfully!')
        return redirect(url_for('home.article', article_id=post.id))   
    form.title.data = post.title
    form.content.data = post.content
    form.category.data = post.category_id
    return render_template('publish.html', form=form)

@home_blueprint.route('/article/<article_id>/delete')
@login_required
def article_del(article_id):
    post = Blog.query.filter_by(id=article_id).first()
    if current_user.name == post.author.name or current_user.name == 'boer':
        db.session.delete(post)
        db.session.commit()
        flash('Delete blog success!')
        return redirect(url_for('home.index'))
    else:
        flash('You are not Superuser!')
        return redirect(url_for('home.index'))

@home_blueprint.route('/category/<category_name>')
def category(category_name):
    category = Category.query.filter_by(name=category_name).first()
    posts = Blog.query.filter_by(category_id=category.id).all()
    return render_template('category.html', posts=posts)

@home_blueprint.route('/publish', methods=['GET', 'POST'])
def publish():
    form = BlogForm()
    choices = Category.get_all()
    form.category.choices = choices
    if form.validate_on_submit():
        post = Blog(form.title.data, form.content.data, current_user.id, form.category.data)
        db.session.add(post)
        db.session.commit()
        flash('Publish blog success!')
        return redirect(url_for('home.index'))
    return render_template('publish.html', form=form)

app/users/views.py
from app import db, bcrypt
from flask import render_template, redirect, url_for, flash, request, Blueprint
from flask.ext.login import login_user, login_required, logout_user, current_user
from .forms import LoginForm, RegisterForm
from app.models import User

users_blueprint = Blueprint(
    'users', __name__,
    template_folder='templates'
)

@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(name=form.username.data).first()
        if user is not None and bcrypt.check_password_hash(
            user.password, form.password.data):
            if form.remember.data:
                login_user(user, remember=True)
            else:
                login_user(user)
            flash('Login success!')
            return redirect(url_for('home.index'))
        else:
            flash('Invalid username or password!')
            return redirect(url_for('users.login'))
    return render_template('login.html', form=form)

@users_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You were logged out.')
    return redirect(url_for('home.index'))

@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        user = User.query.filter_by(name=form.username.data).first()
        if not user:
            user = User(form.username.data, form.email.data, form.password.data)
            db.session.add(user)
            db.session.commit()
            login_user(user)
            flash('Register success and login!')
            return redirect(url_for('home.index'))
        else:
            flash('Username already exists!')
            return redirect(url_for('users.register'))
    return render_template('register.html', form=form)

@users_blueprint.route('/user/<name>')
def profile(name):
    return render_template('profile.html', current_user=current_user)

app/templates/base.html
<!DOCTYPE HTML>
<html>
    <head>
        {% if title %}
        <title>{{ title }}</title>
        {% else %}
        <title>海之博，纳百川</title>
        {% endif %}
        <link href="http://cdn.bootcss.com/uikit/2.24.2/css/uikit.min.css" rel="stylesheet">
        <link href="http://cdn.bootcss.com/uikit/2.24.2/css/components/notify.min.css" rel="stylesheet">
        <script src="http://cdn.bootcss.com/jquery/2.1.4/jquery.min.js"></script>
        <script src="http://cdn.bootcss.com/uikit/2.24.2/js/uikit.min.js"></script>
        <script src="http://cdn.bootcss.com/uikit/2.24.2/js/components/notify.min.js"></script>
        <script src="http://tjs.sjs.sinajs.cn/open/api/js/wb.js" type="text/javascript" charset="utf-8"></script>
        {% block head %}{% endblock %}
    </head>
    <body>
        <!-- start navbar -->
        <nav class="uk-navbar uk-navbar-attached">
            <div class="uk-container uk-container-center">
                <a class="uk-navbar-brand" href="{{ url_for('home.index') }}">Boer-Utopia</a>
                <ul class="uk-navbar-nav">
                    <li><a href="{{ url_for('home.index') }}"><i class="uk-icon-home"></i> Home</a></li>
                    <li><a href="{{ url_for('home.category', category_name='linux') }}"><i class="uk-icon-linux"></i> Linux</a></li>
                    <li><a href="{{ url_for('home.category', category_name='python') }}"><i class="uk-icon-code"></i> Python</a></li>
                    <li><a href="{{ url_for('home.category', category_name='devops') }}"><i class="uk-icon-wrench"></i> DevOps</a></li>
                </ul>
                <div class="uk-navbar-flip">
                    <ul class="uk-navbar-nav uk-hidden-small">
                        {% block nav %}{% endblock %}
                        {% if current_user.is_authenticated %}
                        <li><a href="{{ url_for('users.profile', name=current_user.name) }}"><i class="uk-icon-user"></i>  {{ current_user.name }}</a></li>
                        <li><a href="{{ url_for('home.publish') }}"><i class="uk-icon-edit"></i> Publish</a></li>
                        <li><a href="{{ url_for('users.logout') }}"><i class="uk-icon-sign-out"></i> Logout</a></li>
                        {% else %}
                        <li><a href="{{ url_for('users.login') }}"><i class="uk-icon-sign-in"></i> Login</a></li>
                        <li><a href="{{ url_for('users.register') }}"><i class="uk-icon-registered"></i> Register</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <!-- end navbar -->
        <!-- start middle -->
        <div class="uk-container uk-container-center uk-margin-large-top uk-margin-large-bottom">
            {% with messages = get_flashed_messages() %}
            {% if messages %}
            {% for message in messages %}
            <div class="uk-alert" data-uk-alert>
                <a href="" class="uk-alert-close uk-close"></a>
                <p>{{ message }}</p>
            </div>
            {% endfor %}
            {%endif%}
            {% endwith %}
            <div class="uk-grid">
                {% block content %}{% endblock %}
            </div>
        </div>
        <!-- end middle -->
        <!-- start footer -->
        <div class="uk-margin-large-top" style="background-color:#eee; border-top:1px solid #ccc;">
            <div class="uk-container uk-container-center uk-text-center">
                <div class="uk-panel uk-margin-large-top uk-margin-bottom">
                    <p>Powered by <a href="http://flask.pocoo.org">Flask</a>. Copyright &copy; 2015-2016.</p>
                    <p><a href="http://www.boer.xyz/" target="_blank">www.boer.xyz</a>. All rights reserved.</p>
                    <a href="/">
                        <img style="width: 50px;" class="uk-border-circle" src="http://tp1.sinaimg.cn/2770931324/180/40007524787/1" alt="">
                    </a>
                </div>
            </div>
        </div>
        <!-- end footer -->
    </body>
</html>